services:
  - type: web
    name: event-tracking-backend
    env: docker
    rootDir: demo/demo
    dockerfilePath: Dockerfile
    # Render Free tier might take some time to boot, but it will work
    plan: free
    healthCheckPath: /
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        value: mongodb+srv://msyuthika0_db_user:Yuthika%402005@hackathon.64pgedc.mongodb.net/event_tracker?appName=hackathon
