FROM maven:3.9.4-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

ENV SPRING_DATA_MONGODB_URI="mongodb+srv://msyuthika0_db_user:Yuthika%402005@hackathon.64pgedc.mongodb.net/event_tracker?appName=hackathon"

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]